### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by varac** [metalmatze/transmission-exporter#16]
I'm running transmission-exporter on kubernetes and get the following error:

```
❯ kc logs transmission-exporter-56d58bdb86-7n8pf -f
2019/10/16 16:05:53 starting transmission-exporter
2019/10/16 16:05:53 no .env present
2019/10/16 16:05:57 failed to get session stats: invalid character '<' looking for beginning of value
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7bbbff]

goroutine 20 [running]:
main.(*SessionStatsCollector).Collect(0xc00005c2a0, 0xc00005c5a0)
	/go/src/github.com/metalmatze/transmission-exporter/cmd/transmission-exporter/session_stats_collector.go:118 +0xcf
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v0.9.0-pre1.0.20181010161331-7866eead363e/prometheus/registry.go:430 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v0.9.0-pre1.0.20181010161331-7866eead363e/prometheus/registry.go:522 +0xe12
```

Am I missing sth ? I ignored mounting the transmission config volumes as
suggested in `examples/kubernetes/transmission.yml`, since the
`examples/docker-compose.yml` doesn't use volumens neither (what are the volumes
needed for anyhow ?).

Below is the deployment resource:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: transmission-exporter
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: transmission-exporter
    helm.sh/chart: transmission-exporter-0.1.0
  name: transmission-exporter
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: transmission-exporter
      app.kubernetes.io/name: transmission-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "9190"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: transmission-exporter
        app.kubernetes.io/name: transmission-exporter
    spec:
      containers:
      - env:
        - name: TRANSMISSION_ADDR
          value: https://…
        - name: TRANSMISSION_USERNAME
          value: …
        - name: TRANSMISSION_PASSWORD
          value: …
        - name: WEB_PATH
          value: /metrics
        - name: WEB_ADDR
          value: :19091
        image: metalmatze/transmission-exporter:master
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: transmission-exporter
        ports:
        - containerPort: 19091
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: config
status:
  …
```

**Comment by varac** [comment]
I can also reproduce it with:

    docker run --rm --env-file=.env -p 19091:19091 metalmatze/transmission-exporter:master
    curl localhost:19091/metrics

```
2019/10/16 23:09:45 starting transmission-exporter
2019/10/16 23:09:45 no .env present
2019/10/16 23:09:46 failed to get torrents: invalid character '<' looking for beginning of value
2019/10/16 23:09:46 failed to get session stats: invalid character '<' looking for beginning of value
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7bbbff]

goroutine 32 [running]:
main.(*SessionStatsCollector).Collect(0xc0000ac8a0, 0xc0000acba0)
	/go/src/github.com/metalmatze/transmission-exporter/cmd/transmission-exporter/session_stats_collector.go:118 +0xcf
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v0.9.0-pre1.0.20181010161331-7866eead363e/prometheus/registry.go:430 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v0.9.0-pre1.0.20181010161331-7866eead363e/prometheus/registry.go:522 +0xe12
```

**Comment by varac** [comment]
I can even reproduce it even easier using the go binary directly, using the defaults against transmission 2.94-2ubuntu1 runnning on the same host, with rpc enabled without authentication:

```
❯ ./transmission-exporter
2019/10/17 09:29:02 starting transmission-exporter
2019/10/17 09:29:29 failed to get session stats: invalid character '<' looking for beginning of value
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7bbbff]

goroutine 18 [running]:
main.(*SessionStatsCollector).Collect(0xc000126840, 0xc000126b40)
	/go/src/github.com/metalmatze/transmission-exporter/cmd/transmission-exporter/session_stats_collector.go:118 +0xcf
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v0.9.0-pre1.0.20181010161331-7866eead363e/prometheus/registry.go:430 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v0.9.0-pre1.0.20181010161331-7866eead363e/prometheus/registry.go:522 +0xe12
```

**Comment by varac** [comment]
Damnit, sorry for the noise. PEBKAC, got it working now!

**Comment by varac** [comment]
Well still it would be nice if transmission-exporter would expose a athentication failure as such.
