### ISSUE TITLE
Session.arguments.download-dir-free-space sgementfalut keeping restart，what's wrong？

### ISSUE THREAD

**Issue by xinmans** [metalmatze/transmission-exporter#31]
sudo docker run -d --restart=always -p 19091:19091  metalmatze/transmission-exporter

2022/03/26 04:35:38 starting transmission-exporter
2022/03/26 04:35:53 failed to get session: json: cannot unmarshal number -1 into Go struct field Session.arguments.download-dir-free-space of type uint64
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7ba909]
goroutine 31 [running]:
main.(*SessionCollector).Collect(0xc000102770, 0xc000084c00)
	/go/src/github.com/metalmatze/transmission-exporter/cmd/transmission-exporter/session_collector.go:134 +0xc9
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v0.9.0-pre1.0.20181010161331-7866eead363e/prometheus/registry.go:430 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v0.9.0-pre1.0.20181010161331-7866eead363e/prometheus/registry.go:522 +0xe12
2022/03/26 04:35:54 starting transmission-exporter

**Comment by xinmans** [comment]
fix. in #26
